#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# python 2
export PATH="/usr/local/opt/python/libexec/bin:$PATH"

# pgcli
export PATH="/usr/local/opt/libpq/bin:$PATH"

# envsubst
export PATH="/usr/local/opt/gettext/bin:$PATH"

export VISUAL=vim
export EDITOR=$VISUAL
